posting API and CSS
Nikitak211/poster pull request #4
Opened 2021-10-24 21:36 UTC by Nikitak211

2021-10-27 15:53 UTC, 8o8inCodes approved these changes

2021-10-27 15:53 UTC, 8o8inCodes commented on public/homepage/headerInfo.js
> +window.onload = async function exampleFunction() {
Change to arrow function.

Remember this concept:
Whenever you're assigning a function somewhere like this:
something = function...

Or passing a function into another function like this:

otherfunc(function...)

Always use arrow functions.

Just a standard

2021-10-27 15:53 UTC, 8o8inCodes commented on public/homepage/posting.js
> +    let success = [];
Easier way to doing this is if one of the validation fails, call the "errorOn..." and return in order to exit the function, this way you wont need that `if (success[0] && success[1]) {`

2021-10-27 15:53 UTC, 8o8inCodes commented on public/homepage/posts.js
> +    `${['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'][date.getMonth()]} ${date.getDate()}, ${date.getFullYear()} ${date.getHours()}:${(date.getMinutes() < 10 ? '
It's nice that you've done that, but try to find a better way with less code and without defining every month. try researching about date formatting in javascript

2021-10-27 15:53 UTC, 8o8inCodes commented on public/homepage/posts.js
> +  `;
Brings me some old memories

2021-10-27 15:53 UTC, 8o8inCodes commented on public/login/login.js
> +            errorOn(input, "cannot be blank")
Same here, if there is a bad value, call this function and then just return

2021-10-27 15:53 UTC, 8o8inCodes commented on public/register/register.js
> +	const passwordValidation = (value, value2, input) => {
When I looked at it, I didn't know what "input" is, give a better name

2021-10-27 15:57 UTC, Nikitak211 commented on public/homepage/posts.js
> +  `;
what should i do

2021-10-27 15:58 UTC, 8o8inCodes commented on public/homepage/posts.js
> +  `;
Nothing, just fun memories lol

2021-10-27 17:16 UTC, 8o8inCodes requested changes

2021-10-27 17:16 UTC, 8o8inCodes commented on public/homepage/headerInfo.js
> +window.onload = exampleFunction = async ()  =>  {
No need to name "example function" do it like this:
`window.onload = async () => {`

2021-10-27 17:16 UTC, 8o8inCodes commented on public/login/login.js
> +    emptyField(emailValue, email)
Currently after these functions, doesn't matter if they have error or not, the code will continue further to the fetch always.
So make sure you stop it from executing by making "emptyField" return true or false if there was an error or not, and then add
`if(!emptyField(passwordValue, password)) return;`

2021-10-27 17:16 UTC, 8o8inCodes commented on public/login/login.js
> +    emptyField(emailValue, email)
Do the same in all the cases where you changed it

2021-10-27 17:16 UTC, 8o8inCodes commented on public/register/register.js
> +	usernameValidation(usernameValue, username)
Same here

2021-10-27 19:34 UTC, 8o8inCodes requested changes

2021-10-27 19:34 UTC, 8o8inCodes commented on public/login/login.js
>          } else {
No need for this else statement anymore, because if value is empty, it will exit anyway

2021-10-27 19:34 UTC, 8o8inCodes commented on public/register/register.js
>  		} else {
Same here

2021-10-27 19:34 UTC, 8o8inCodes commented on public/register/register.js
>  		} else {
Just leave the 
```js
successOn(inputToggle)
return true;
```

After the if

2021-10-31 15:16 UTC, 8o8inCodes approved these changes

2021-10-31 16:13 UTC, merged